### ISSUE TITLE
Feedback on Music 5000 FPGA Notes

### ISSUE THREAD

**Issue by chrisjj** [hoglet67/Music5000#1]
EDITED 2023-09-27 with clarifications.

 Music 5000 FPGA Notes 
https://github.com/hoglet67/Music5000/wiki/Home/9dcc516e66bd769aeceb85412aa27134c5c07fcb

> It stores the Channel Registers for each of the 16 Voices. 

It stores the Channel Registers for each of the 16 channels. 

> Each voice is made up of a pair of channels (a normal and an alternative), and each channel is controlled by 6 separate registers (frequency lo, frequency mid, frequency hi, amplitude, waveform and control)

Each channel has two sets of registers, normal and alternative (though better named A and B, I think), each comprising six registers (frequency lo, frequency mid, frequency hi, amplitude, waveform and control).

> The reason for the paired channel registers is to support complex forms of frequency modulation.

The reason for the two sets of registers is to support modulation of any controllable parameter, inc. frequency, amplitude, phase (for synchronisation) etc.

> For example, the it is possible to program the different characteristics in each channel in the pair (e.g. different frequencies), and then use the adjacent channel to control the switching between them.

For example, it is possible to program the different characteristics in each set in for one channel (e.g. different frequencies), and then use the channel [s]two[/s] one position (in register order) earlier in the table of sixteen channels to switch between them at audio frequency.

**Comment by hoglet67** [comment]
Thanks Chris.

I've updated the Wiki page to included these suggestions.
